{{- range .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  name: repo-{{ .name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: {{ .name | quote }}
  url: {{ .url | quote }}
  username: {{ .username | quote }}
  password: {{ .password | quote }}
type: Opaque
---
{{- end }}
